---
services:
  service-a:
    build:
      args:
        - self=container_a
        - other=container_b
      context: .
    container_name: container_a
    hostname: host_a
  service-b:
    build:
      args:
        - self=container_b
        - other=container_a
      context: .
    container_name: container_b
    hostname: host_b
version: '3'
...
